export const news = {
  FETCH_ALL_NEWS : 'FETCH_ALL_NEWS',
  FETCH_NEWS_BY_SID : 'FETCH_NEWS_BY_SID',
  FETCH_TOP_HEADLINES : 'FETCH_TOP_HEADLINES',
  FETCH_RELATED_NEWS : 'FETCH_RELATED_NEWS',
  UPDATE_SELECTED_SOURCE: 'UPDATE_SELECTED_SOURCE',
  FETCH_SOURCES : 'FETCH_SOURCES',
  FETCH_SELECTED_NEWS : 'FETCH_SELECTED_NEWS'
}